import { Download, MoreHorizontal } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

export function ReportsList() {
  // This would typically come from your database
  const reports = {
    timeTracking: [
      {
        id: "1",
        name: "Hours by Project",
        description: "Total hours logged per project",
        lastGenerated: "Today, 9:30 AM",
      },
      {
        id: "2",
        name: "Hours by Employee",
        description: "Total hours logged per employee",
        lastGenerated: "Today, 9:30 AM",
      },
      {
        id: "3",
        name: "Billable vs. Non-Billable",
        description: "Comparison of billable and non-billable hours",
        lastGenerated: "Yesterday, 4:15 PM",
      },
    ],
    financial: [
      {
        id: "4",
        name: "Project Profitability",
        description: "Profit margin analysis by project",
        lastGenerated: "Yesterday, 4:15 PM",
      },
      {
        id: "5",
        name: "Client Revenue",
        description: "Revenue generated by client",
        lastGenerated: "Oct 8, 2024",
      },
      {
        id: "6",
        name: "Budget vs. Actual",
        description: "Comparison of budgeted vs. actual hours and costs",
        lastGenerated: "Oct 8, 2024",
      },
    ],
    performance: [
      {
        id: "7",
        name: "Team Utilization",
        description: "Utilization rates for team members",
        lastGenerated: "Oct 7, 2024",
      },
      {
        id: "8",
        name: "Project Timeline",
        description: "Project completion against timeline",
        lastGenerated: "Oct 7, 2024",
      },
      {
        id: "9",
        name: "Task Breakdown",
        description: "Hours spent by task category",
        lastGenerated: "Oct 5, 2024",
      },
    ],
  }

  return (
    <Tabs defaultValue="timeTracking" className="space-y-4">
      <TabsList>
        <TabsTrigger value="timeTracking">Time Tracking</TabsTrigger>
        <TabsTrigger value="financial">Financial</TabsTrigger>
        <TabsTrigger value="performance">Performance</TabsTrigger>
      </TabsList>
      <TabsContent value="timeTracking" className="space-y-4">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {reports.timeTracking.map((report) => (
            <Card key={report.id}>
              <CardHeader className="flex flex-row items-start justify-between space-y-0">
                <div>
                  <CardTitle>{report.name}</CardTitle>
                  <CardDescription>{report.description}</CardDescription>
                </div>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" size="icon">
                      <MoreHorizontal className="h-4 w-4" />
                      <span className="sr-only">Actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem>View Report</DropdownMenuItem>
                    <DropdownMenuItem>Edit Parameters</DropdownMenuItem>
                    <DropdownMenuItem>Schedule</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Last generated: {report.lastGenerated}</div>
                <Button variant="outline" size="sm" className="mt-4 w-full">
                  <Download className="mr-2 h-4 w-4" />
                  Download
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </TabsContent>
      <TabsContent value="financial" className="space-y-4">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {reports.financial.map((report) => (
            <Card key={report.id}>
              <CardHeader className="flex flex-row items-start justify-between space-y-0">
                <div>
                  <CardTitle>{report.name}</CardTitle>
                  <CardDescription>{report.description}</CardDescription>
                </div>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" size="icon">
                      <MoreHorizontal className="h-4 w-4" />
                      <span className="sr-only">Actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem>View Report</DropdownMenuItem>
                    <DropdownMenuItem>Edit Parameters</DropdownMenuItem>
                    <DropdownMenuItem>Schedule</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Last generated: {report.lastGenerated}</div>
                <Button variant="outline" size="sm" className="mt-4 w-full">
                  <Download className="mr-2 h-4 w-4" />
                  Download
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </TabsContent>
      <TabsContent value="performance" className="space-y-4">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {reports.performance.map((report) => (
            <Card key={report.id}>
              <CardHeader className="flex flex-row items-start justify-between space-y-0">
                <div>
                  <CardTitle>{report.name}</CardTitle>
                  <CardDescription>{report.description}</CardDescription>
                </div>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" size="icon">
                      <MoreHorizontal className="h-4 w-4" />
                      <span className="sr-only">Actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem>View Report</DropdownMenuItem>
                    <DropdownMenuItem>Edit Parameters</DropdownMenuItem>
                    <DropdownMenuItem>Schedule</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Last generated: {report.lastGenerated}</div>
                <Button variant="outline" size="sm" className="mt-4 w-full">
                  <Download className="mr-2 h-4 w-4" />
                  Download
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </TabsContent>
    </Tabs>
  )
}
